### ISSUE TITLE
DEX Order Book page

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/ergo-explorer#66]
Originally described in https://github.com/aslesarenko/ergo-tool/issues/26

### Motivation 
Command to show current [order book](https://en.wikipedia.org/wiki/Order_book_(trading)) for a given token, i.e. a table with Sell and Buy orders by price.
So that all sell orders are above all buy orders.

UPDATE:
The order book is pretty standard thing, you can look at any exchange. The buy and sell orders should be ordered by Token Price. 
The Token Price, however, you need to compute yourself, because the orders contain Token Amount and Erg Amount only so TokenPrice = ErgAmount / TokenAmount
Thus one can sell 1 token for 100 erg so the TokenPrice = 100/1
or he can buy 100 tokens for 1000 ergs co TokenPrice = 1000 / 100
So this two orders should be sorted accordingly based on price.
The computation should take into account "Number of decimals" from [EIP-4](https://github.com/ergoplatform/eips/blob/master/eip-0004.md)

### Parameters
- token id;

#### 1. Fetch all unspent sell and buy order contracts(boxes) with Appkit's [BlockchainContext.getUnspentBoxesForErgoTreeTemplate](http://github.com/aslesarenko/ergo-appkit/blob/00ce6c27b27631d6bf5aade621a05791096ab3bc/lib-api/src/main/java/org/ergoplatform/appkit/BlockchainContext.java#L70-L70) 
(or at `transactions/boxes/byErgoTreeTemplate/unspent/{ergoTreeTemplate}`)
This API call was added in https://github.com/ergoplatform/explorer-back/pull/230
Use the following template bytes: 
- `eb027300d1eded91b1a57301e6c6b2a5730200040ed801d60193e4c6b2a5730300040ec5a7eded92c1b2a57304007305720193c2b2a5730600d07307` for sell order;
- `eb027300d1eded91b1a57301e6c6b2a5730200040ed803d601e4c6b2a5730300020c4d0ed602eded91b172017304938cb27201730500017306928cb27201730700027308d60393e4c6b2a5730900040ec5a7eded720293c2b2a5730a00d0730b7203` for buy orders;

Both are generated by [`SellerContract.contractTemplate`](http://github.com/aslesarenko/ergo-tool/blob/4b487e9ef797e77c11b31e080e0f716d017896b5/src/main/scala-2.12/org/ergoplatform/appkit/ergotool/dex/CreateSellOrderCmd.scala#L107-L107) and 
[`BuyerContract.contractTemplate`](http://github.com/aslesarenko/ergo-tool/blob/4b487e9ef797e77c11b31e080e0f716d017896b5/src/main/scala-2.12/org/ergoplatform/appkit/ergotool/dex/CreateBuyOrderCmd.scala#L110-L110) which use contracts from fv sigma branch - [src](http://github.com/ScorexFoundation/sigmastate-interpreter/blob/42e55cbfd093252b8005e4607970764dd6610cbe/contract-verification/src/main/scala/sigmastate/verification/contract/AssetsAtomicExchange.scala#L12-L45).
Keep in mind that these contracts will be changed soon due to https://github.com/aslesarenko/ergo-tool/issues/30 

#### 2. Filter fetched contracts(boxes) by token id.
- Sell order box should have token id and amount in `box.tokens` and token price encoded in its contract. Token price should be in [`ErgoTree.constants(5)`](http://github.com/aslesarenko/ergo-tool/blob/4b487e9ef797e77c11b31e080e0f716d017896b5/src/main/scala-2.12/org/ergoplatform/appkit/ergotool/dex/CreateSellOrderCmd.scala#L120-L124).
- Buy order box should have token id and amount encoded in the contract and token price in `box.value`. Token id should be in [`ErgoTree.constants(6)`](http://github.com/aslesarenko/ergo-tool/blob/4b487e9ef797e77c11b31e080e0f716d017896b5/src/main/scala-2.12/org/ergoplatform/appkit/ergotool/dex/CreateBuyOrderCmd.scala#L128-L131) and the token amount should be in [`ErgoTree.constants(8)`](http://github.com/aslesarenko/ergo-tool/blob/4b487e9ef797e77c11b31e080e0f716d017896b5/src/main/scala-2.12/org/ergoplatform/appkit/ergotool/dex/CreateBuyOrderCmd.scala#L131-L134).

Expect these places to change with a new contract to be introduced in https://github.com/aslesarenko/ergo-tool/issues/30 

#### 3. Get token name by token id
Should be done as Coinbarn does at https://github.com/coinbarn/ergo-ts/blob/80551350e882585f7c24ce642e9bc750badc76a3/src/explorer.ts#L64
or easier after https://github.com/ergoplatform/explorer-back/issues/232 is done.

**Comment by aslesarenko** [comment]
1) I suggest we do it in a right way from the first version, so that we don't need to come back to this again (other than mirgate to new explorer-backend)
2) To avoid hardcoding templates and allow future development we can experiment with running explorer node.js app using GraalVM. [See some success stories](https://habr.com/ru/company/odnoklassniki/blog/480808/) This will open all Appkit API to be used in explorer UI, something worth the efforts, we can even write a blog post about it (team work so to say:).
3) Data filtering should be done in the explorer, buy passing optional tokenId as parameter there. In fact it is better pass a bunch of optional parameters and compose the query depending on this.
We don't want unnecessary data to be pulled out of backend.

**Comment by greenhat** [comment]
@aslesarenko  token price becomes tricky when erg amount includes dex fee.

**Comment by deadit** [comment]
done
