### ISSUE TITLE
DEX Issued Token page

### ISSUE THREAD

**Issue by greenhat** [ergoplatform/ergo-explorer#67]
Originally described in https://github.com/aslesarenko/ergo-tool/issues/25

### Motivation
Issued token is a special box created according to [EIP-4](https://github.com/ergoplatform/eips/blob/master/eip-0004.md).
In order to buy existing token one needs to find it's id.
Thus we need a command which:
1) list all issued tokens (respecting `--limit-list` option)
2) filter tokens by name (R4 register)
3) Output table with columns (name, id, amount, decimals, description) 

### Implementation notes.
Box that issued a token with `token id` can be fetched with `assets/[token id]/issuingBox` call.
Check details at https://github.com/ergoplatform/explorer-backend/blob/rest-api/modules/explorer-api/src/main/scala/org/ergoplatform/explorer/http/api/v0/defs/AssetsEndpointDefs.scala

**Comment by deadit** [comment]
Done
