### ISSUE TITLE
Show costs for blocks, transactions, and inputs.

### ISSUE THREAD

**Issue by jasondavies** [ergoplatform/ergo-explorer#75]
For each input, the total cost of that input should be shown.

For each transaction, the total cost should be shown and then a breakdown:
- input costs as above
- initialisation cost

The total cost for a whole block should also be shown.

**Comment by deadit** [comment]
Could you please provide some more information about what you want? Maybe some screens from website where you want to see the cost.

**Comment by jasondavies** [comment]
This is mainly because it's quite difficult at the moment to understand how much particular boxes cost to spend.  For example, [this transaction](https://explorer.ergoplatform.com/en/transactions/dcef60cb9604a62eda29f38639fe75c87e6386815f846caa5740c0a742808f0a):

- Each input could include an associated "cost".
- Under "summary", show "initialisation cost" and "total cost" (total cost = initialisation cost + sum(input cost)).

This is not a high priority request but I think developers will find it useful.

**Comment by deadit** [comment]
This repository contains explorer frontend :) I think you should write it to  https://github.com/ergoplatform/explorer-backend

**Comment by deadit** [comment]
@jasondavies I've created issue at backend repo, you can watch it here - https://github.com/ergoplatform/explorer-backend/issues/31

**Comment by jasondavies** [comment]
Thanks! Yes, I wasn't sure if this should be a frontend issue or a backend issue.
